"""initial

Revision ID: 910e7737cdfa
Revises: 
Create Date: 2026-07-25 16:25:04.776605

"""
import pgvector.sqlalchemy.vector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '910e7737cdfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_practice_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('applicable_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_best_practice_memory_practice_name'), 'best_practice_memory', ['practice_name'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.Enum('NASDAQ', 'NYSE', 'LSE', 'HKEX', 'TSE', 'SSE', 'SZSE', 'BSE', 'NSE', 'TSX', 'ASX', 'FWB', 'EPA', 'BIT', 'SIX', 'OTHER', name='exchange'), nullable=False),
    sa.Column('sector', sa.Enum('ENERGY', 'MATERIALS', 'INDUSTRIALS', 'CONSUMER_DISCRETIONARY', 'CONSUMER_STAPLES', 'HEALTH_CARE', 'FINANCIALS', 'INFORMATION_TECHNOLOGY', 'COMMUNICATION_SERVICES', 'UTILITIES', 'REAL_ESTATE', 'UNCLASSIFIED', name='sector'), nullable=False),
    sa.Column('industry', sa.Enum('SOFTWARE', 'SEMICONDUCTORS', 'IT_SERVICES', 'HARDWARE', 'CYBERSECURITY', 'AI_ML', 'FINTECH', 'ECOMMERCE', 'BIOTECH', 'PHARMACEUTICALS', 'MEDICAL_DEVICES', 'HEALTHCARE_SERVICES', 'DIAGNOSTICS', 'BANKING', 'INSURANCE', 'ASSET_MANAGEMENT', 'PAYMENTS', 'RETAIL', 'FOOD_BEVERAGE', 'APPAREL', 'AUTOMOTIVE', 'ENTERTAINMENT', 'AEROSPACE', 'MANUFACTURING', 'LOGISTICS', 'CONSTRUCTION', 'OIL_GAS', 'RENEWABLE_ENERGY', 'UTILITIES', 'CHEMICALS', 'METALS_MINING', 'REIT', 'PROPERTY_DEVELOPMENT', 'OTHER', name='industry'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('business_model', sa.Text(), nullable=False),
    sa.Column('competitive_advantage', sa.Text(), nullable=False),
    sa.Column('headquarters', sa.String(length=255), nullable=False),
    sa.Column('founded_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('ceo', sa.String(length=255), nullable=False),
    sa.Column('cfo', sa.String(length=255), nullable=False),
    sa.Column('coo', sa.String(length=255), nullable=False),
    sa.Column('board_members', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('major_shareholders', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ipo_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ipo_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ipo_shares', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('enterprise_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('domain_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_events_aggregate_id'), 'domain_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_domain_events_event_type'), 'domain_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_domain_events_timestamp'), 'domain_events', ['timestamp'], unique=False)
    op.create_index('ix_events_aggregate_version', 'domain_events', ['aggregate_id', 'version'], unique=False)
    op.create_table('failure_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('failure_id', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.Enum('DISCOVERY', 'COLLECTION', 'FUNDAMENTAL', 'MARKET', 'RISK', 'SENTIMENT', 'DECISION', 'REPORT', 'MEMORY', 'REFLECTION', name='agentname'), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('attempted_fix', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('HALLUCINATION', 'WRONG_CALCULATION', 'BAD_FINANCIAL_ASSUMPTION', 'MISSING_API', 'RATE_LIMIT', 'WRONG_PROMPT', 'PARSING_FAILURE', 'DUPLICATE_DATA', 'TIMEOUT', 'AUTHENTICATION', 'INVALID_RESPONSE', 'NETWORK_ERROR', 'DATA_QUALITY', 'MODEL_ERROR', 'UNKNOWN', name='failurecategory'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('similarity_hash', sa.String(length=64), nullable=False),
    sa.Column('last_occurrence', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ipo_symbol', sa.String(length=20), nullable=True),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_failure_agent_category', 'failure_memory', ['agent_name', 'category'], unique=False)
    op.create_index(op.f('ix_failure_memory_agent_name'), 'failure_memory', ['agent_name'], unique=False)
    op.create_index(op.f('ix_failure_memory_category'), 'failure_memory', ['category'], unique=False)
    op.create_index(op.f('ix_failure_memory_error_type'), 'failure_memory', ['error_type'], unique=False)
    op.create_index(op.f('ix_failure_memory_failure_id'), 'failure_memory', ['failure_id'], unique=True)
    op.create_index(op.f('ix_failure_memory_ipo_symbol'), 'failure_memory', ['ipo_symbol'], unique=False)
    op.create_index(op.f('ix_failure_memory_resolved'), 'failure_memory', ['resolved'], unique=False)
    op.create_index(op.f('ix_failure_memory_similarity_hash'), 'failure_memory', ['similarity_hash'], unique=False)
    op.create_index('ix_failure_unresolved', 'failure_memory', ['resolved', 'last_occurrence'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('IPO_DISCOVERY', 'DATA_COLLECTION', 'FUNDAMENTAL_ANALYSIS', 'MARKET_ANALYSIS', 'RISK_ANALYSIS', 'SENTIMENT_ANALYSIS', 'DECISION_SYNTHESIS', 'REPORT_GENERATION', 'MEMORY_CONSOLIDATION', 'REFLECTION_RUN', 'OUTCOME_VERIFICATION', 'CLEANUP', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SCHEDULED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'RETRYING', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_scheduled_at'), 'jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_status_scheduled', 'jobs', ['status', 'scheduled_at'], unique=False)
    op.create_index('ix_jobs_type_status', 'jobs', ['job_type', 'status'], unique=False)
    op.create_table('knowledge_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_memory_concept'), 'knowledge_memory', ['concept'], unique=True)
    op.create_index(op.f('ix_knowledge_memory_domain'), 'knowledge_memory', ['domain'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_type', sa.Enum('PROMPT_IMPROVEMENT', 'TOOL_USAGE', 'DATA_SOURCE', 'REASONING_PATTERN', 'RISK_FACTOR', 'SCORING_ADJUSTMENT', 'WEIGHT_ADJUSTMENT', 'THRESHOLD_CHANGE', 'ANTI_PATTERN', 'BEST_PRACTICE', name='lessontype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('do', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('dont', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('best_practices', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('anti_patterns', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('known_bugs', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('prompt_improvements', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applicable_agents', sa.ARRAY(sa.Enum('DISCOVERY', 'COLLECTION', 'FUNDAMENTAL', 'MARKET', 'RISK', 'SENTIMENT', 'DECISION', 'REPORT', 'MEMORY', 'REFLECTION', name='agentname')), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_lesson_type'), 'lessons', ['lesson_type'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.Enum('SHORT_TERM', 'LONG_TERM', 'VECTOR', 'FAILURE', 'SUCCESS', 'KNOWLEDGE', 'EXPERIENCE', 'BEST_PRACTICE', 'REFLECTION', name='memorytype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ttl_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_created_at'), 'memory_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_memory_entries_memory_type'), 'memory_entries', ['memory_type'], unique=False)
    op.create_table('success_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('success_id', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.Enum('DISCOVERY', 'COLLECTION', 'FUNDAMENTAL', 'MARKET', 'RISK', 'SENTIMENT', 'DECISION', 'REPORT', 'MEMORY', 'REFLECTION', name='agentname'), nullable=False),
    sa.Column('strategy_description', sa.Text(), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('tool_sequence', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('api_sequence', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('reuse_count', sa.Integer(), nullable=False),
    sa.Column('last_reused', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ipo_symbol', sa.String(length=20), nullable=True),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_success_memory_agent_name'), 'success_memory', ['agent_name'], unique=False)
    op.create_index(op.f('ix_success_memory_context_hash'), 'success_memory', ['context_hash'], unique=False)
    op.create_index(op.f('ix_success_memory_ipo_symbol'), 'success_memory', ['ipo_symbol'], unique=False)
    op.create_index(op.f('ix_success_memory_success_id'), 'success_memory', ['success_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cost_of_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_expenses', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('eps_basic', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_diluted', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('shares_outstanding', sa.Integer(), nullable=True),
    sa.Column('shares_diluted', sa.Integer(), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('short_term_investments', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('long_term_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('short_term_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('working_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('investing_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('financing_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('capex', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('roic', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('debt_to_ebitda', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('interest_coverage', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('revenue_growth_qoq', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('earnings_growth_yoy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('earnings_growth_qoq', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fcf_growth_yoy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_statements_company_id'), 'financial_statements', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_statements_period_end'), 'financial_statements', ['period_end'], unique=False)
    op.create_index('ix_financials_company_period', 'financial_statements', ['company_id', 'period_end'], unique=False)
    op.create_index('ix_financials_company_period_type', 'financial_statements', ['company_id', 'period_type', 'period_end'], unique=False)
    op.create_table('ipos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.Enum('NASDAQ', 'NYSE', 'LSE', 'HKEX', 'TSE', 'SSE', 'SZSE', 'BSE', 'NSE', 'TSX', 'ASX', 'FWB', 'EPA', 'BIT', 'SIX', 'OTHER', name='exchange'), nullable=False),
    sa.Column('sector', sa.Enum('ENERGY', 'MATERIALS', 'INDUSTRIALS', 'CONSUMER_DISCRETIONARY', 'CONSUMER_STAPLES', 'HEALTH_CARE', 'FINANCIALS', 'INFORMATION_TECHNOLOGY', 'COMMUNICATION_SERVICES', 'UTILITIES', 'REAL_ESTATE', 'UNCLASSIFIED', name='sector'), nullable=False),
    sa.Column('industry', sa.Enum('SOFTWARE', 'SEMICONDUCTORS', 'IT_SERVICES', 'HARDWARE', 'CYBERSECURITY', 'AI_ML', 'FINTECH', 'ECOMMERCE', 'BIOTECH', 'PHARMACEUTICALS', 'MEDICAL_DEVICES', 'HEALTHCARE_SERVICES', 'DIAGNOSTICS', 'BANKING', 'INSURANCE', 'ASSET_MANAGEMENT', 'PAYMENTS', 'RETAIL', 'FOOD_BEVERAGE', 'APPAREL', 'AUTOMOTIVE', 'ENTERTAINMENT', 'AEROSPACE', 'MANUFACTURING', 'LOGISTICS', 'CONSTRUCTION', 'OIL_GAS', 'RENEWABLE_ENERGY', 'UTILITIES', 'CHEMICALS', 'METALS_MINING', 'REIT', 'PROPERTY_DEVELOPMENT', 'OTHER', name='industry'), nullable=False),
    sa.Column('status', sa.Enum('ANNOUNCED', 'FILED', 'PRICED', 'LISTED', 'WITHDRAWN', 'POSTPONED', 'CANCELLED', name='ipostatus'), nullable=False),
    sa.Column('announced_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priced_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('listed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_price_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_price_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priced_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shares_offered', sa.Integer(), nullable=True),
    sa.Column('shares_sold', sa.Integer(), nullable=True),
    sa.Column('overallotment_option', sa.Boolean(), nullable=False),
    sa.Column('overallotment_shares', sa.Integer(), nullable=True),
    sa.Column('expected_valuation_low', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('expected_valuation_high', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('priced_valuation', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('post_money_valuation', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('lead_underwriters', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('co_managers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('lockup_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lockup_days', sa.Integer(), nullable=True),
    sa.Column('prospectus_url', sa.String(length=500), nullable=False),
    sa.Column('filing_urls', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipos_company_id'), 'ipos', ['company_id'], unique=False)
    op.create_index(op.f('ix_ipos_expected_date'), 'ipos', ['expected_date'], unique=False)
    op.create_index(op.f('ix_ipos_status'), 'ipos', ['status'], unique=False)
    op.create_index(op.f('ix_ipos_symbol'), 'ipos', ['symbol'], unique=True)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ipo_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PARTIAL', name='analysisstatus'), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('financial_strength_score', sa.Float(), nullable=False),
    sa.Column('growth_potential_score', sa.Float(), nullable=False),
    sa.Column('market_opportunity_score', sa.Float(), nullable=False),
    sa.Column('management_quality_score', sa.Float(), nullable=False),
    sa.Column('risk_level_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bull_case', sa.Text(), nullable=False),
    sa.Column('bear_case', sa.Text(), nullable=False),
    sa.Column('key_risks', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('key_catalysts', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('investment_strategy', sa.Enum('AGGRESSIVE_BUY', 'BUY', 'ACCUMULATE', 'HOLD', 'REDUCE', 'SELL', 'AVOID', 'WATCH', name='investmentstrategy'), nullable=False),
    sa.Column('time_horizon', sa.Enum('INTRADAY', 'SHORT_TERM', 'MEDIUM_TERM', 'LONG_TERM', 'VERY_LONG_TERM', name='timehorizon'), nullable=False),
    sa.Column('risk_level', sa.Enum('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', 'EXTREME', name='risklevel'), nullable=False),
    sa.Column('sentiment', sa.Enum('VERY_NEGATIVE', 'NEGATIVE', 'NEUTRAL', 'POSITIVE', 'VERY_POSITIVE', name='sentimentlabel'), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_drivers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('agent_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_company_id'), 'analyses', ['company_id'], unique=False)
    op.create_index(op.f('ix_analyses_ipo_id'), 'analyses', ['ipo_id'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('investment_theses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('bull_case', sa.Text(), nullable=False),
    sa.Column('bear_case', sa.Text(), nullable=False),
    sa.Column('key_drivers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('key_risks', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('catalysts', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('assumptions', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('prediction_type', sa.Enum('PRICE_CHANGE_1D', 'PRICE_CHANGE_1W', 'PRICE_CHANGE_1M', 'PRICE_CHANGE_3M', 'PRICE_CHANGE_6M', 'PRICE_CHANGE_12M', 'VOLATILITY', 'VOLUME', 'OUTPERFORM_MARKET', 'UNDERPERFORM_MARKET', 'BANKRUPTCY_RISK', 'ACQUISITION_TARGET', name='predictiontype'), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('time_horizon', sa.String(length=50), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=False),
    sa.Column('assumptions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('outcome_status', sa.Enum('PENDING', 'VERIFIED', 'EXPIRED', 'INCONCLUSIVE', name='outcomestatus'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_analysis_id'), 'predictions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_type'), 'predictions', ['prediction_type'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ipo_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('ipo_overview', sa.Text(), nullable=False),
    sa.Column('company_background', sa.Text(), nullable=False),
    sa.Column('industry_analysis', sa.Text(), nullable=False),
    sa.Column('financial_analysis', sa.Text(), nullable=False),
    sa.Column('valuation_analysis', sa.Text(), nullable=False),
    sa.Column('risk_analysis', sa.Text(), nullable=False),
    sa.Column('management_assessment', sa.Text(), nullable=False),
    sa.Column('sentiment_analysis', sa.Text(), nullable=False),
    sa.Column('bull_case', sa.Text(), nullable=False),
    sa.Column('bear_case', sa.Text(), nullable=False),
    sa.Column('investment_thesis', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('key_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('financial_tables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('charts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disclaimers', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['ipo_id'], ['ipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_analysis_id'), 'reports', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_reports_ipo_id'), 'reports', ['ipo_id'], unique=False)
    op.create_table('risk_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('factor', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', 'EXTREME', name='risklevel'), nullable=False),
    sa.Column('probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('impact', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_factors_analysis_id'), 'risk_factors', ['analysis_id'], unique=False)
    op.create_table('score_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('sub_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_components_analysis_id'), 'score_components', ['analysis_id'], unique=False)
    op.create_table('experience_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ipo_symbol', sa.String(length=20), nullable=False),
    sa.Column('situation_description', sa.Text(), nullable=False),
    sa.Column('prediction_made', sa.Text(), nullable=False),
    sa.Column('actual_outcome', sa.Text(), nullable=False),
    sa.Column('learning', sa.Text(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('outcome_id', sa.UUID(), nullable=True),
    sa.Column('confidence_at_prediction', sa.Float(), nullable=False),
    sa.Column('time_to_outcome_days', sa.Integer(), nullable=True),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experience_ipo_symbol', 'experience_memory', ['ipo_symbol'], unique=False)
    op.create_index(op.f('ix_experience_memory_ipo_symbol'), 'experience_memory', ['ipo_symbol'], unique=False)
    op.create_table('reflection_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('ipo_symbol', sa.String(length=20), nullable=False),
    sa.Column('prediction_type', sa.Enum('PRICE_CHANGE_1D', 'PRICE_CHANGE_1W', 'PRICE_CHANGE_1M', 'PRICE_CHANGE_3M', 'PRICE_CHANGE_6M', 'PRICE_CHANGE_12M', 'VOLATILITY', 'VOLUME', 'OUTPERFORM_MARKET', 'UNDERPERFORM_MARKET', 'BANKRUPTCY_RISK', 'ACQUISITION_TARGET', name='predictiontype'), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('error', sa.Float(), nullable=False),
    sa.Column('mistakes_identified', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('correct_assumptions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('missing_factors', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('lessons_extracted', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('prompt_improvements', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('strategy_changes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('knowledge_updates', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflection_memory_ipo_symbol'), 'reflection_memory', ['ipo_symbol'], unique=False)
    op.create_index(op.f('ix_reflection_memory_prediction_id'), 'reflection_memory', ['prediction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reflection_memory_prediction_id'), table_name='reflection_memory')
    op.drop_index(op.f('ix_reflection_memory_ipo_symbol'), table_name='reflection_memory')
    op.drop_table('reflection_memory')
    op.drop_index(op.f('ix_experience_memory_ipo_symbol'), table_name='experience_memory')
    op.drop_index('ix_experience_ipo_symbol', table_name='experience_memory')
    op.drop_table('experience_memory')
    op.drop_index(op.f('ix_score_components_analysis_id'), table_name='score_components')
    op.drop_table('score_components')
    op.drop_index(op.f('ix_risk_factors_analysis_id'), table_name='risk_factors')
    op.drop_table('risk_factors')
    op.drop_index(op.f('ix_reports_ipo_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_analysis_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_predictions_prediction_type'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_analysis_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('investment_theses')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_ipo_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_company_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_ipos_symbol'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_status'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_expected_date'), table_name='ipos')
    op.drop_index(op.f('ix_ipos_company_id'), table_name='ipos')
    op.drop_table('ipos')
    op.drop_index('ix_financials_company_period_type', table_name='financial_statements')
    op.drop_index('ix_financials_company_period', table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_period_end'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_company_id'), table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_success_memory_success_id'), table_name='success_memory')
    op.drop_index(op.f('ix_success_memory_ipo_symbol'), table_name='success_memory')
    op.drop_index(op.f('ix_success_memory_context_hash'), table_name='success_memory')
    op.drop_index(op.f('ix_success_memory_agent_name'), table_name='success_memory')
    op.drop_table('success_memory')
    op.drop_index(op.f('ix_memory_entries_memory_type'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_created_at'), table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_lessons_lesson_type'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_knowledge_memory_domain'), table_name='knowledge_memory')
    op.drop_index(op.f('ix_knowledge_memory_concept'), table_name='knowledge_memory')
    op.drop_table('knowledge_memory')
    op.drop_index('ix_jobs_type_status', table_name='jobs')
    op.drop_index('ix_jobs_status_scheduled', table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_scheduled_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_failure_unresolved', table_name='failure_memory')
    op.drop_index(op.f('ix_failure_memory_similarity_hash'), table_name='failure_memory')
    op.drop_index(op.f('ix_failure_memory_resolved'), table_name='failure_memory')
    op.drop_index(op.f('ix_failure_memory_ipo_symbol'), table_name='failure_memory')
    op.drop_index(op.f('ix_failure_memory_failure_id'), table_name='failure_memory')
    op.drop_index(op.f('ix_failure_memory_error_type'), table_name='failure_memory')
    op.drop_index(op.f('ix_failure_memory_category'), table_name='failure_memory')
    op.drop_index(op.f('ix_failure_memory_agent_name'), table_name='failure_memory')
    op.drop_index('ix_failure_agent_category', table_name='failure_memory')
    op.drop_table('failure_memory')
    op.drop_index('ix_events_aggregate_version', table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_timestamp'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_event_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_aggregate_id'), table_name='domain_events')
    op.drop_table('domain_events')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_best_practice_memory_practice_name'), table_name='best_practice_memory')
    op.drop_table('best_practice_memory')
    # ### end Alembic commands ###
