"""add_source_tracking_llm_metadata_chat_settings

Revision ID: 5179cb70c1da
Revises: dfc213da6510
Create Date: 2026-08-09 00:12:40.782085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5179cb70c1da'
down_revision = 'dfc213da6510'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('ipo_symbol', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_ipo_symbol'), 'conversations', ['ipo_symbol'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('deployment_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_settings_key'), 'deployment_settings', ['key'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=True),
    sa.Column('ipo_symbol', sa.String(length=20), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_ipo_symbol'), 'chat_messages', ['ipo_symbol'], unique=False)
    
    # Add columns as nullable first, then set defaults, then make NOT NULL
    op.add_column('analyses', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    op.add_column('analyses', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.add_column('analyses', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('financial_statements', sa.Column('source_reference', sa.String(length=500), nullable=True))
    op.add_column('financial_statements', sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ipos', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('ipos', sa.Column('source_reference', sa.String(length=500), nullable=True))
    op.add_column('ipos', sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Set defaults for existing rows
    op.execute("UPDATE analyses SET llm_provider = '', llm_model = '', tokens_used = 0, cost_usd = 0")
    op.execute("UPDATE financial_statements SET source_reference = ''")
    op.execute("UPDATE ipos SET source = '', source_reference = ''")
    
    # Now make columns NOT NULL
    op.alter_column('analyses', 'llm_provider', nullable=False)
    op.alter_column('analyses', 'llm_model', nullable=False)
    op.alter_column('analyses', 'tokens_used', nullable=False)
    op.alter_column('analyses', 'cost_usd', nullable=False)
    op.alter_column('financial_statements', 'source_reference', nullable=False)
    op.alter_column('ipos', 'source', nullable=False)
    op.alter_column('ipos', 'source_reference', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ipos', 'source_updated_at')
    op.drop_column('ipos', 'source_reference')
    op.drop_column('ipos', 'source')
    op.drop_column('financial_statements', 'source_updated_at')
    op.drop_column('financial_statements', 'source_reference')
    op.drop_column('analyses', 'cost_usd')
    op.drop_column('analyses', 'tokens_used')
    op.drop_column('analyses', 'llm_model')
    op.drop_column('analyses', 'llm_provider')
    op.drop_index(op.f('ix_chat_messages_ipo_symbol'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_deployment_settings_key'), table_name='deployment_settings')
    op.drop_table('deployment_settings')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_ipo_symbol'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
