"""Add source attribution and missing IPO fields

Revision ID: a36517ab3df8
Revises: e29b1e56c9da
Create Date: 2026-08-10 16:38:08.151370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36517ab3df8'
down_revision = 'e29b1e56c9da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipos', sa.Column('issue_size', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('ipos', sa.Column('face_value', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ipos', sa.Column('lot_size', sa.Integer(), nullable=True))
    op.add_column('ipos', sa.Column('registrar', sa.String(length=255), nullable=True))
    op.add_column('ipos', sa.Column('collector_version', sa.String(length=50), nullable=True))
    op.add_column('ipos', sa.Column('data_quality_score', sa.Float(), nullable=True))
    op.add_column('ipos', sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ipos', 'last_verified_at')
    op.drop_column('ipos', 'data_quality_score')
    op.drop_column('ipos', 'collector_version')
    op.drop_column('ipos', 'registrar')
    op.drop_column('ipos', 'lot_size')
    op.drop_column('ipos', 'face_value')
    op.drop_column('ipos', 'issue_size')
    # ### end Alembic commands ###
