"""add_source_tracking_and_llm_metadata

Revision ID: dfc213da6510
Revises: 910e7737cdfa
Create Date: 2026-08-09 00:06:49.405313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc213da6510'
down_revision = '910e7737cdfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
